#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/usr/local/home/akozlov/prog/tecnet/x86_64/.libs/libnrnmech.so" "$@"
